### ISSUE TITLE
Clean up SQL scripts under amp-sql

### ISSUE THREAD

**Issue by BrianSipos** [NASA-AMMOS/anms#103]
The current [`amp-sql/Dockerfile`](https://github.com/NASA-AMMOS/anms/blob/main/amp-sql/Dockerfile) renames a bunch of individual files rather than giving them appropriate names in the repo itself and using a `COPY postgres/Database_Scripts/Tables/*.sql ...` and similar to get them into the image.

There also appear to be abandoned `Dockerfile` and `docker-compose.yml` files in that file tree which should be removed if they are not actually in use.

This is a longer-term sustainment improvement and not a defect.

**Comment by BrianSipos** [comment]
The renaming will simplify the Dockerfile contents, and the files themselves should be relocated into the `dtnma-tools` repository if they are directly needed by the AMP Manager runtime. I don't know if there is a split that some are needed and some not, or if they are just all needed by AMP Manager.

**Comment by mfarina1** [comment]
Relevant to ANMS backend dev because it's about updating and fixing the amp-sql database portion of the ANMS
