### ISSUE TITLE
ANMS_FUN_BLD_001 (Time-Based Rule) - Macro

### ISSUE THREAD

**Issue by goldekt1** [NASA-AMMOS/anms#109]
A macro was successfully created to execute three previously defined time-based rules.  The expected table of rules was not generated and the expected amp and bp agent full reports were not generated.

**Comment by d-linko** [comment]
a macro can only contain controls or other macros. so you would need to use the gen_tbr control to add new TBR rules 
so send `ari:/IANA:amp_agent/CTRL.add_macro("test_mac",ari:/MAC.test_tbr1,[ari:/IANA:amp_agent/CTRL.add_tbr(ari:/tbr.t1,10,30,5,[ari:/IANA:amp_agent/CTRL.gen_rpts([ari:/IANA:amp_agent/EDD.num_tbr],["ipn:1.7"])],"test_mac"),ari:/IANA:amp_agent/CTRL.add_tbr(ari:/tbr.t2,0,10,20,[ari:/IANA:amp_agent/CTRL.gen_rpts([ari:/IANA:amp_agent/RPTT.full_report],["ipn:1.7"])],"test_mac")])` to add the macro then send `ari:/MAC.test_tbr1` to run that macro
