### ISSUE TITLE
ANMS_FUN_BLD_002 (Generate Reports) - Setup

### ISSUE THREAD

**Issue by goldekt1** [NASA-AMMOS/anms#110]
Successfully generated control for a table of ADMS, but the table was not listed in the Reports Sent.  This was also noted in other test cases using a table of ADMS.

**Comment by d-linko** [comment]
table issue tracked by https://github.com/NASA-AMMOS/anms/issues/121

**Comment by mfarina1** [comment]
Covered by #121
