### ISSUE TITLE
ANMS_FUN_BLD_002 (Generate Reports) - BP full report

### ISSUE THREAD

**Issue by goldekt1** [NASA-AMMOS/anms#112]
Ran the test for a  bp agent full report. Noted:
•	ADM defines num_pend_fwd as UNIT, Reports Received placed these under String Values
•	ADM defines a number of EDDs as UINTs, the Reports Received has these under UVAST Values
•	Reports Received has values (under UVAST) that do not appear in the Agent details bp full report.  These appear to be: src_bytes_by_priority, discarded_bundles, discarded_bytes.
•	There are 3 instances of the src_bytes_by_priority (1, 2, 4), the value could be associated with the second instance.  There is an associated priority mask to interpret the values.
•	The values for src_bytes_by_priority and discarded_bundles are the same, should they be?

**Comment by d-linko** [comment]
should be fixed by dtnma-tools updates, potential fix is updating the bp-agent ADM to use uvast
