### ISSUE TITLE
ANMS_FUN_BLD_003 (Report Templates)

### ISSUE THREAD

**Issue by goldekt1** [NASA-AMMOS/anms#114]
Currently cannot generate table of ADMs, table of report templates, table of table templates.  This limits the specified verification in the test case.

A new report template was added, no errors were noted.  A report to display the current number of report templates was created and executed.  The number of report templates incremented by 1.  A description of the report template was created and submitted, but only the time was displayed in the resulting report.

The same was noted when a description of an existing report was requested.

The control to delete the new report template was created and submitted.  Since the table of reports could not be generated, the number of report templates was retrieved, and it decreased by 1.

**Comment by d-linko** [comment]
https://github.com/NASA-AMMOS/anms/issues/121

**Comment by mfarina1** [comment]
Covered under #121
