### ISSUE TITLE
Fix all Dependabot issues marked "High"

### ISSUE THREAD

**Issue by mfarina1** [NASA-AMMOS/anms#137]
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/63
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/61
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/55
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/53
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/52
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/47
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/45
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/44
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/43
- [ ] https://github.com/NASA-AMMOS/anms/security/dependabot/42
- [ ] https://github.com/NASA-AMMOS/anms/security/dependabot/40
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/39
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/36
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/22
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/16
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/9
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/6
- [x] https://github.com/NASA-AMMOS/anms/security/dependabot/2

**Comment by d-linko** [comment]
issues 
- https://github.com/NASA-AMMOS/anms/security/dependabot/42
- https://github.com/NASA-AMMOS/anms/security/dependabot/40
currently don't have patched versions so leaving open for now
