### ISSUE TITLE
ANMS_FUN_BLD_007 (EDDs): EDDs with REF

### ISSUE THREAD

**Issue by d-linko** [NASA-AMMOS/anms#39]
It was noted several EDDs listed for selection in the Build tab Select ARI field have a type of (REF:xx), where xx is a number.  Another instance of this EDD also exists, but has the expected data type (e.g., STR).  Selecting an EDD with the REF creates an error when the control is submitted.

It would seem the EDDs with REF should be removed from the selection list.

**Comment by mfarina1** [comment]
Relevant to ANMS backend dev because it's about updating and fixing the amp-sql database portion of the ANMS
