### ISSUE TITLE
Filter ARI builder input on "ctrl"

### ISSUE THREAD

**Issue by njbrunner** [NASA-AMMOS/anms#56]
The ARI builder input on the build page shows all possible ARI commands but should only display "ctrl" commands

### Acceptance Criteria:
- [ ] ARI builder input only shows "ctrl" and "macro" commands
- [ ] [Optional] control to allow all commands to show

**Comment by d-linko** [comment]
should also be able to see macros

**Comment by d-linko** [comment]
handled by https://github.com/NASA-AMMOS/anms/pull/78, which updated the UI
