### ISSUE TITLE
ANMS_FUN_ADM_001 (ADM Listing)

### ISSUE THREAD

**Issue by goldekt1** [NASA-AMMOS/anms#85]
Two ADMs were selected for download from the ADM option:  amp_agent and ion_admin.

It was noted the downloaded amp_agent ADM lacked the "Mac" section found in the IEFT document (draft-birrane-dtn-adm-agent-05).

It was noted the IETF ion_admin specification and the downloaded ADM compared except the downloaded file contained under MDAT: {"name": "enum", "type": "INT", "value": "7"} .  This definition was included in other ADMs downloaded, but did not appear in the IEFT ion_admin specification.

**Comment by d-linko** [comment]
replaced with #118
