### ISSUE TITLE
ANMS_FUN_DAP_002 (Received Reports) - UINT values order

### ISSUE THREAD

**Issue by goldekt1** [NASA-AMMOS/anms#90]
It was noted in the Received Reports panel that the order of the UINT values for an AMP agent full report did not follow the order specified in the corresponding ADM.  The order of these values varied between the different AMP agent reports displayed.  Without a consistent order, the user is not able to determine what the values displayed represent.

**Comment by d-linko** [comment]
seems stable after updating reports table with https://github.com/NASA-AMMOS/anms/pull/120
