### ISSUE TITLE
ANMS_FUN_DAP_004 (Message Groups)

### ISSUE THREAD

**Issue by goldekt1** [NASA-AMMOS/anms#92]
Multiple agents were selected in the Agents option and a time-based rule was created to produce multiple bp agent full reports, but the rule did not execute. The test case was run with only single requests for bp agent full reports.  The single bp agent full report was reflected in the Message Groups per Minute display, but only one of the multiple agents selected was associated with the report.  Supplying the optional receiving managers parameter seemed to resolve the issue.

**Comment by d-linko** [comment]
test step instruction
