### ISSUE TITLE
ANMS_FUN_DAP_005 (User Created Views)

### ISSUE THREAD

**Issue by goldekt1** [NASA-AMMOS/anms#93]
A new user panel was created using the SQL defined in the user guide, but the resulting panel displayed the message ‘No Data’.  When the SQL was executed against the database table , vw_rpt_entries, 31 rows satisfied the query.  Resolved by selecting the correct version of the database for the query.

**Comment by d-linko** [comment]
is the amp_core selected as the data source?

**Comment by goldekt1** [comment]
Yes, it was.

From: David Linko ***@***.***>
Sent: Friday, August 16, 2024 10:00 AM
To: NASA-AMMOS/anms ***@***.***>
Cc: Goldee, Karen T. ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [NASA-AMMOS/anms] ANMS_FUN_DAP_005 (User Created Views) (Issue #93)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




is the amp_core selected as the data source?

**Comment by goldekt1** [comment]
OK, I tried it again and it is working.  Perhaps the last time I selected the amp_core_mysql.

From: David Linko ***@***.***>
Sent: Friday, August 16, 2024 10:00 AM
To: NASA-AMMOS/anms ***@***.***>
Cc: Goldee, Karen T. ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [NASA-AMMOS/anms] ANMS_FUN_DAP_005 (User Created Views) (Issue #93)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




is the amp_core selected as the data source?
